queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success~=build \(2.13.\d+\)

pull_request_rules:

  - name: Label dependency-update PRs
    conditions:
      - author=scala-steward
    actions:
      label:
        add: [dependencies, scala]

  - name: Merge dependency-update PRs
    conditions:
      - and:
        - label=dependencies
        - base=master
        - check-success~=build \(2.13.\d+\)
    actions:
      queue:
        name: default
        method: squash
