name: Test
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        scalaVersion: ["2.13.7"]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v12

      - name: Test
        run: sbt ++${{matrix.scalaVersion}} test

