name: Test
on:
  push:
    branches: [master]
    tags: [ v* ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        scalaVersion: ["2.13.7"]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v12

      - uses: actions/cache@v2
        name: Cache node_modules
        with:
          path: "**/main/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/main/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - uses: actions/cache@v2
        name: Cache scala targets
        with:
          path: "**/target"
          key: ${{ runner.os }}-scala-target-${{ github.sha }}

      - name: Test
        run: sbt ++${{matrix.scalaVersion}} test

      # - name: Debug over SSH (tmate)
      #   # if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true

  publish:
    needs: [build]
    # if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
    strategy:
      matrix:
        os: [ubuntu-20.04]
        scala: [2.13.7]
        java: [adopt@1.8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v12
        with:
          java-version: 8

      - name: Cache SBT
        uses: coursier/cache-action@v6

      - uses: actions/cache@v2
        name: Cache node_modules
        with:
          path: "**/main/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/main/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - uses: actions/cache@v2
        name: Cache scala targets
        with:
          path: "**/target"
          key: ${{ runner.os }}-scala-target-${{ github.sha }}

      - uses: olafurpg/setup-gpg@v3
      - name: Publish
        run: sbt version "git status" ci-release "git status"
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
